[env:waveshare_s3_amoled]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I include
    ; nofrendo
    -I lib/arduino-nofrendo/src
    -I lib/arduino-nofrendo/src/nes
    -I lib/arduino-nofrendo/src/cpu
    -DNOFRENDO_DEBUG_DISABLE
    ; Debug: uncomment to scan NES RAM for health addresses (prints to serial) 全自动扫描HP的地址在，把地址添加到/game/game_profiles.cfg文件里面
    ; -DHP_SCAN_ENABLE  ; ← 注释掉以启用震动反馈（HP_SCAN 和震动互斥）
    ; LVGL
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    ; NES
    -DNES_EMULATOR_ENABLED
    
    ; 优化
    -O2

lib_deps =
    lvgl/lvgl@8.4.0
    esphome/ESP32-audioI2S@^2.3.0

board_build.f_cpu = 240000000L